//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Focusin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Focusin.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break duration.
        /// </summary>
        public static string BreakDuration {
            get {
                return ResourceManager.GetString("BreakDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current session:.
        /// </summary>
        public static string CurrentSession {
            get {
                return ResourceManager.GetString("CurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default settings.
        /// </summary>
        public static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable screen time-out.
        /// </summary>
        public static string DisableScreenTimeOut {
            get {
                return ResourceManager.GetString("DisableScreenTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sound.
        /// </summary>
        public static string EnableSound {
            get {
                return ResourceManager.GetString("EnableSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable vibration.
        /// </summary>
        public static string EnableVibration {
            get {
                return ResourceManager.GetString("EnableVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color.
        /// </summary>
        public static string ForegroundColor {
            get {
                return ResourceManager.GetString("ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focusin is an application based on the pomodoro technique. What is the pomodoro technique? The pomodoro technique is a time management method. The technique uses a timer to break down periods of work into 25-minute intervals separated by breaks..
        /// </summary>
        public static string InstructionsHeader {
            get {
                return ResourceManager.GetString("InstructionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Decide on the task to be done.
        /// </summary>
        public static string InstructionsList1 {
            get {
                return ResourceManager.GetString("InstructionsList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Set the pomodoro timer to 25 minutes.
        /// </summary>
        public static string InstructionsList2 {
            get {
                return ResourceManager.GetString("InstructionsList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Work on the task until the timer rings.
        /// </summary>
        public static string InstructionsList3 {
            get {
                return ResourceManager.GetString("InstructionsList3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Take a short break (5 minutes).
        /// </summary>
        public static string InstructionsList4 {
            get {
                return ResourceManager.GetString("InstructionsList4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. After four sessions, take a long break (15-20 mins)..
        /// </summary>
        public static string InstructionsList5 {
            get {
                return ResourceManager.GetString("InstructionsList5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are five basic steps to implementing the technique:.
        /// </summary>
        public static string InstructionsListHeader {
            get {
                return ResourceManager.GetString("InstructionsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long break duration.
        /// </summary>
        public static string LongBreakDuration {
            get {
                return ResourceManager.GetString("LongBreakDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long break frequency.
        /// </summary>
        public static string LongBreakFrequency {
            get {
                return ResourceManager.GetString("LongBreakFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session duration.
        /// </summary>
        public static string SessionDuration {
            get {
                return ResourceManager.GetString("SessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings reset.
        /// </summary>
        public static string SettingsReset {
            get {
                return ResourceManager.GetString("SettingsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reset your settings to default?.
        /// </summary>
        public static string SettingsResetMessage {
            get {
                return ResourceManager.GetString("SettingsResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support: foxandxss@gmail.com.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer Sound from freesound.org @ Herbert Boland.
        /// </summary>
        public static string TimerSoundCopy {
            get {
                return ResourceManager.GetString("TimerSoundCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view more from Foxandxss.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
    }
}
